# copy of default, with train and val batches reduced for quicker debugging

accelerator: gpu
strategy: null
devices: 1
accumulate_grad_batches: 1 # Gradient accumulation every n batches
max_epochs: 200
                           # accelerator: ddp # Automatically set if gpus > 1
gradient_clip_val: null
log_every_n_steps: 10
limit_train_batches: 0.1   # train on full dataset, can be used to toggle quick run
limit_val_batches: 0.1     # validate on full dataset, can be used to toggle quick run
enable_model_summary: false # Can turn on if RichModelSummary is disabled
track_grad_norm: -1  
